
baseURL = 'https://www.rexxla.org/blog'
languageCode = 'en-us'
title = 'RexxLA'
theme = "ananke"
#featured_image = 'images/NetRexxLogo.jpg'
#paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
DefaultContentLanguage = "en"
resourceDir = "./resources"

SectionPagesMenu = "main"
sidebarrecentlimit = 5
# markup.highlight.noClasses=false
 custom_css = ["_code.css","syntax.css"]
[params]
  body_classes = "avenir bg-white"
  post_content_classes = "avenir bg-white"	
  site_logo = 'images/rexxla.png'
  pagination = 8
  copyright = "RexxLA 2022"
  recent_posts_number = 8
  background_color_class = "bg-navy"
  description = "News and Blogs from RexxLA"
  favicon = ""
      text_color = ""
  author = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"



[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-light'
    tabWidth = 2
    
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/NetRexx"

[markup.goldmark.renderer]
unsafe = true
