baseURL = 'https://www.rexxla.org/blog'
languageCode = 'en-us'
title = 'RexxLA'
theme = "ananke"
#featured_image = 'images/NetRexxLogo.jpg'
SectionPagesMenu = "main"
sidebarrecentlimit = 	5
# markup.highlight.noClasses=false
 custom_css = ["_code.css","syntax.css"]
[params]
  body_classes = "avenir bg-white"
  post_content_classes = "avenir bg-white"	
  site_logo = 'images/rexxla.png'
  pagination = 15
  copyright = "RexxLA 2022"
  recent_posts_number = 8
  background_color_class = "bg-navy"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/NetRexx"
  
